server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.144.163
    port: 6379
    database: 0
    password:
  cache:
    type: redis
    redis:
      cache-null-values: true # ????null????????
      time-to-live: 10000 # ?????? ??

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml