server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_info?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.144.163
    port: 6379
    database: 0
    password:
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 10000
  kafka:
    bootstrap-servers: 192.168.144.163:9092
    consumer:
      group-id: userGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
